### PR TITLE
adopted to v1.0 api

### PR DESCRIPTION
**Pull request by damooo**
@shashikiranraifox anna, this branch is with code adopted to v1.0

### CODE REVIEW

**Comment by shashikiranraifox** [comment]
As discussed over call,  i have the following comment to make:

1. Support for Version 0 API has been completely removed.
2. In one of the earlier discussions with @sai-r-susarla, it was informed that we had to support both the versions[0 and 1] and the application will have the intelligence to do so based on API version declared in endpoints.service.ts file.
3. In today's discussion, @damooo informed that creating a Release Tag would suffice for Version 0.

@sai-r-susarla  & @damooo  please confirm this approach. Based on your confirmation, I shall merge it.
In the meanwhile I shall go ahead and verify all the changes in v1_mod branch.

**Comment by shashikiranraifox** [comment]
@damooo I have tested the features on the deployed client.  All the features are working but Uploading a Single page is not working. Uploading pages in bulk is working but uploading a single page at a time is not working. 
I shall check the API is available on Swagger and make the fix myself.

For now I shall approve the merge after creating a Release tag for version 0.

**Comment by damooo** [comment]
ok anna. i thought, uploading single page is not required now. hence i left it. if it is required, we can do repetition of uploading multiple pages with each time array with single file.

**Comment by shashikiranraifox** [comment]
> ok anna. i thought, uploading single page is not required now. hence i left it. if it is required, we can do repetition of uploading multiple pages with each time array with single file.

No problem, I shall do it after the merge.

**Pull request merged**
